#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

here=`env - PATH=$PATH pwd`
parent=`dirname $here`

echo 'Creating symlink daemontools -> daemontools-0.76...'
rm -f daemontools
ln -s daemontools-0.76 daemontools
mv -f daemontools ..

echo 'Making command links in $HOME/usr/command...'
mkdir -p $HOME/usr/command
for i in `cat package/commands`
do
  rm -f $HOME/usr/command/$i'{new}'
  ln -s $parent/daemontools/command/$i $HOME/usr/command/$i'{new}'
  mv -f $HOME/usr/command/$i'{new}' $HOME/usr/command/$i
done
echo 'Making compatibility links in $HOME/usr/local/bin...'
mkdir -p $HOME/usr/local/bin
for i in `cat package/commands`
do
  rm -f $HOME/usr/local/bin/$i'{new}'
  ln -s $HOME/usr/command/$i $HOME/usr/local/bin/$i'{new}'
  mv -f $HOME/usr/local/bin/$i'{new}' $HOME/usr/local/bin/$i
done
